name: Run PHP Style Check
description: 'Runs a php style check based on wilkware/symcons style'

runs:
  using: "composite"
  steps:
      - run: git submodule update --init -- .style
        shell: bash
      - run: wget https://cs.symfony.com/download/php-cs-fixer-v2.phar
        shell: bash
      - run: PHP_CS_FIXER_IGNORE_ENV=1 php php-cs-fixer-v2.phar fix --config=.style/.php_cs -v --dry-run --allow-risky=yes --path-mode=intersection .
        shell: bash
